name: Deploy via FTP

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      APP_ENV: prod

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install dependencies
        run: composer install --no-dev --optimize-autoloader --no-scripts

      - name: Create .env for build
        run: |
          echo "APP_ENV=prod" > .env
          echo "APP_SECRET=dummy_build_secret" >> .env
          echo "mysql://yx2loi_Drissben:Wakeskate.92@yx2loi.myd.infomaniak.com:3306/yx2loi_novadanse?serverVersion=10.11.2-MariaDB&charset=utf8mb4" >> .env

      - name: Install JS vendors
        run: php bin/console importmap:install

      - name: Compile assets
        run: php bin/console asset-map:compile

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: /sites/TON-DOMAINE/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            .env
            .env.local
            var/cache/**
            var/log/**